In [1]:
import torch
import numpy as np

In [3]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
print(x_data)
print(x_data.shape)

tensor([[1, 2],
        [3, 4]])
torch.Size([2, 2])


In [4]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(np_array)
print(type(np_array))
print(x_np)
print (x_np == x_data)

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>
tensor([[1, 2],
        [3, 4]])
tensor([[True, True],
        [True, True]])


In [5]:
# retains the properties of x_data
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor: \n {x_ones} \n")

#overrides the datatype of x_data
x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor: \n {x_rand} \n")


Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.5840, 0.4054],
        [0.6565, 0.9661]]) 



In [12]:
shape = (2, 3 )
#print(len(shape))
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

2
Random Tensor: 
 tensor([[0.8981, 0.9398, 0.3522],
        [0.6694, 0.7787, 0.1440]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [13]:
tensor = torch.rand(3, 4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [24]:
tensor = torch.ones(4, 4)
tensor[:,:] = 2
print(tensor)

tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]])


In [19]:
t1 = torch.cat([tensor, tensor+1, tensor+2], dim=1)
print(t1)
print(t1.shape)

tensor([[1., 0., 1., 1., 2., 1., 2., 2., 3., 2., 3., 3.],
        [1., 0., 1., 1., 2., 1., 2., 2., 3., 2., 3., 3.],
        [1., 0., 1., 1., 2., 1., 2., 2., 3., 2., 3., 3.],
        [1., 0., 1., 1., 2., 1., 2., 2., 3., 2., 3., 3.]])
torch.Size([4, 12])


In [25]:
# This computes the element-wise product
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)} \n")
# Alternative syntax:
print(f"tensor * tensor \n {(1+tensor) * (1+tensor)}")

tensor.mul(tensor) 
 tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]]) 

tensor * tensor 
 tensor([[9., 9., 9., 9.],
        [9., 9., 9., 9.],
        [9., 9., 9., 9.],
        [9., 9., 9., 9.]])


In [27]:
T_tensor = tensor.T
print(T_tensor)
print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor.T)} \n")
# Alternative syntax:
print(f"tensor @ tensor.T \n {tensor @ tensor.T}")

tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]])
tensor.matmul(tensor.T) 
 tensor([[16., 16., 16., 16.],
        [16., 16., 16., 16.],
        [16., 16., 16., 16.],
        [16., 16., 16., 16.]]) 

tensor @ tensor.T 
 tensor([[16., 16., 16., 16.],
        [16., 16., 16., 16.],
        [16., 16., 16., 16.],
        [16., 16., 16., 16.]])


In [30]:
tens = torch.rand(2,4)
print(tens)
print(tens.T)
print(f"tensor @ tensor.T \n {tens @ tens.T}")

tensor([[0.3892, 0.0988, 0.7627, 0.6742],
        [0.2361, 0.9586, 0.7461, 0.7630]])
tensor([[0.3892, 0.2361],
        [0.0988, 0.9586],
        [0.7627, 0.7461],
        [0.6742, 0.7630]])
tensor @ tensor.T 
 tensor([[1.1974, 1.2700],
        [1.2700, 2.1134]])


In [31]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]]) 

tensor([[7., 7., 7., 7.],
        [7., 7., 7., 7.],
        [7., 7., 7., 7.],
        [7., 7., 7., 7.]])


In [32]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]
t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [34]:
n = np.ones(5)
t = torch.from_numpy(n)
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
