In [1]:
import torch, torchvision
model = torchvision.models.resnet18(pretrained=True)
data = torch.rand(1, 3, 64, 64)
labels = torch.rand(1, 1000)

/Users/L029235/.pyenv/versions/3.8.13/envs/torch-1.12/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and will be removed in 0.15, please use 'weights' instead.
  warnings.warn(
/Users/L029235/.pyenv/versions/3.8.13/envs/torch-1.12/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and will be removed in 0.15. The current behavior is equivalent to passing `weights=ResNet18_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet18_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Downloading: "https://download.pytorch.org/models/resnet18-f37072fd.pth" to /Users/L029235/.cache/torch/hub/checkpoints/resnet18-f37072fd.pth
100.0%


In [8]:
print(f"Data:\n{data.shape}\n{data}")
print(f"Label:\n{labels}")

Data:
torch.Size([1, 3, 64, 64])
tensor([[[[0.0095, 0.2399, 0.3234,  ..., 0.7080, 0.8762, 0.7803],
          [0.1512, 0.4236, 0.9718,  ..., 0.6720, 0.3077, 0.5509],
          [0.8978, 0.8950, 0.9929,  ..., 0.7457, 0.7026, 0.2589],
          ...,
          [0.6142, 0.3932, 0.0089,  ..., 0.8349, 0.5336, 0.7096],
          [0.5228, 0.2688, 0.7100,  ..., 0.3987, 0.0338, 0.2448],
          [0.7033, 0.2098, 0.2000,  ..., 0.8361, 0.9407, 0.4395]],

         [[0.2210, 0.7243, 0.0738,  ..., 0.2423, 0.6153, 0.9702],
          [0.4089, 0.2347, 0.9279,  ..., 0.3170, 0.0437, 0.2981],
          [0.2046, 0.3132, 0.3924,  ..., 0.6615, 0.8832, 0.8012],
          ...,
          [0.8792, 0.2192, 0.8577,  ..., 0.6187, 0.0268, 0.0284],
          [0.1739, 0.2565, 0.2653,  ..., 0.4569, 0.3677, 0.0107],
          [0.2902, 0.5904, 0.0555,  ..., 0.1338, 0.8682, 0.9012]],

         [[0.8274, 0.7505, 0.1036,  ..., 0.0010, 0.9607, 0.8277],
          [0.1360, 0.7574, 0.9169,  ..., 0.3515, 0.4465, 0.0295],
         

In [12]:
# forward pass
prediction = model(data)
print(f"Prediction:\n{prediction.shape}\n{prediction}")

Prediction:
torch.Size([1, 1000])
tensor([[-6.6323e-01, -5.5824e-01, -4.4836e-01, -1.6375e+00, -6.8243e-01,
         -1.9243e-02, -4.3171e-01,  4.2404e-01,  2.8109e-01, -7.6903e-01,
         -1.0937e+00, -9.7463e-01, -2.6924e-01, -1.4074e+00, -1.0509e+00,
         -8.5762e-01, -9.5830e-01, -4.3960e-01, -6.0292e-01, -6.0138e-01,
         -1.4032e+00, -6.9204e-01, -1.6585e+00,  1.0368e-01, -1.1891e+00,
         -1.1880e+00, -5.3122e-01, -8.8044e-01, -6.3203e-01, -3.6554e-01,
         -6.7467e-01, -4.6575e-01, -1.5097e-01, -3.4015e-01, -3.8976e-01,
         -4.0869e-01,  6.2062e-01, -7.7053e-01, -2.0955e-01, -4.7944e-02,
         -6.2842e-01, -5.6348e-01, -1.0315e+00, -4.2024e-01, -7.3733e-01,
         -6.6478e-01, -7.6701e-01, -1.9016e-01, -1.4770e+00, -1.3544e+00,
         -8.2151e-01,  6.4381e-01, -1.5887e-01, -6.2336e-01, -2.3826e-01,
         -1.2717e+00, -2.9659e-01, -1.4010e+00, -2.1126e-01, -2.9372e-01,
          9.1144e-01,  1.8131e-01, -7.1101e-02,  1.8772e-01, -7.2645e-01,
    

In [11]:
err = prediction - labels
print(f"Error:\n{err.shape}\n{err}")

Error:
torch.Size([1, 1000])
tensor([[-7.6670e-01, -5.7032e-01, -5.5905e-01, -1.7403e+00, -8.3707e-01,
         -7.7300e-01, -5.6999e-01,  1.2304e-01, -2.0518e-01, -1.3926e+00,
         -1.7580e+00, -1.0205e+00, -1.2413e+00, -1.4170e+00, -1.0662e+00,
         -1.3764e+00, -1.2561e+00, -9.3574e-01, -9.8801e-01, -9.9742e-01,
         -1.5742e+00, -1.2681e+00, -1.7161e+00, -6.8480e-01, -2.0711e+00,
         -1.5936e+00, -9.7959e-01, -1.0190e+00, -9.5982e-01, -3.8833e-01,
         -1.4599e+00, -1.3031e+00, -9.3715e-01, -7.6836e-01, -1.3616e+00,
         -1.0008e+00,  2.4871e-01, -8.3686e-01, -6.6585e-01, -9.3742e-01,
         -1.1013e+00, -6.0320e-01, -1.6007e+00, -1.1507e+00, -1.5989e+00,
         -1.0117e+00, -1.0016e+00, -3.1906e-01, -1.6770e+00, -1.4118e+00,
         -1.3592e+00,  1.6220e-01, -5.8753e-01, -9.7602e-01, -6.9486e-01,
         -1.5168e+00, -1.2550e+00, -1.4460e+00, -2.1991e-01, -9.5809e-01,
          2.4901e-01, -3.9652e-01, -8.7455e-01, -5.7116e-01, -1.3722e+00,
         

In [16]:
loss = err.sum()
print(f"Loss:\n{type(loss)}\n{loss.shape}\n{loss}")

Loss:
<class 'torch.Tensor'>
torch.Size([])
-495.739013671875


In [24]:
#loss.backward()
print(loss.grad)

None


In [25]:
optim = torch.optim.SGD(model.parameters(), lr=1e-2, momentum=0.9)

In [26]:
optim.step() #gradient descent